### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by clever98** [sirius/aws-cpp-sdk-cognito-auth#1]
Can this code be compiled with VisualStudio on windows?
I got several errors with VS.

**Comment by sirius** [comment]
I haven't tried, but I don't see why it shouldn't. Its C++11, but you'll of course need OpenSSL headers. What kind of errors do you get?

**Comment by clever98** [comment]
It's fixed with pre-built aws-sdk. It might be my bad while I build the sdks.
Sorry for bothering.
